
## 50MHz FPGA main clock (usually generated by oscillator)
create_clock -name clk50    -period  20.000  [get_ports clk50]

## 60MHz FT232H chip clock (generated by FT232H)
create_clock -name ftdi_clk -period  16.667  [get_ports ftdi_clk]

#create_clock -name clk0       -period  20.000  [get_ports *pll1|clk[0]*]
#create_clock -name clklvds    -period  8.000   [get_ports *pll1|clk[1]*]
#create_clock -name clklvdsout -period  40.000  [get_ports *pll1|clk[2]*]
derive_pll_clocks

derive_clock_uncertainty -add

## Declare that these two clocks are asynchronous
set_clock_groups -asynchronous -group {clk50 *pll1|clk[0]* *pll1|clk[1]* *pll1|clk[2]*} -group {ftdi_clk}

